### ISSUE TITLE
Add more ligatures

### ISSUE THREAD

**Issue by kitten** [kitten/dank-mono#10]
This is an umbrella task for ligatures that have been requested. If not otherwise noted, the ligatures are planned to be implemented, some might be "under consideration", which means they might not be added.

### Released Ligatures

- [x] `=>`
- [x] `==`
- [x] `!=`
- [x] `===`
- [x] `!==`
- [x] `[|`
- [x] `|]`
- [x] `{|`
- [x] `|}`
- [x] `++`
- [x] `|>`

### Next Release

- [x] `/*`
- [x] `*/`
- [ ] `/>` (under consideration)
- [x] `->`
- [x] `<-`
- [x] `.=`

### Future

- [ ] `//`
- [ ] `####`, `###`, `##`

Operators like `>=` and `<=` might not be added as ligatures for them involve symbols that "break" the visual similarity to their actual composition.

**Comment by kitten** [comment]
@narqo sure, makes sense :+1:

**Comment by danielpost** [comment]
Would you consider adding .= to the list, similar to Fira Code? I use it quite often in PHP.

Also, considering #6 is closed, is this the correct place to add a +1 for <= and >=? If so, +1 from me.

**Comment by pardom** [comment]
Is there a date yet for the next release? I don't see any [milestones](https://github.com/kitten/dank-mono/milestones).

**Comment by kitten** [comment]
@pardom I don’t plan to set fixed dates for releases. Sorry 😅

That being said, all changes for the next release are done and I’m trying to squeeze Greek letters into this release as well. But I might kick them out of this release and publish another patch release tonight

**Comment by lowmess** [comment]
if `/>` gets made, it would make sense for `</` to exist as well

**Comment by kitten** [comment]
Moved to Spectrum https://spectrum.chat/?t=98e86889-ed8d-4a7a-ad18-5206ffb75f93
