### ISSUE TITLE
Letters with diacritics

### ISSUE THREAD

**Issue by hedinne** [kitten/dank-mono#11]
The diacritical marks above most uppercase letters are barely visable. This is not a problem with lower case letters.

![2018-05-04_15-25-53](https://user-images.githubusercontent.com/7573694/39636462-c8e1a756-4faf-11e8-854d-8c14c91270b9.png)
In the picture above are the letters "ÉÓÚÍÝÁ" and "EOUIYA".

All the best, 
Héðinn

**Comment by kitten** [comment]
Hiya, sorry about that. It's because there's unfortunately barely any space to add them. I might push them up and outside of the letters' boundaries, but that might cause other problems. Let me see what I can do. I don't think there'll be many satisfying solutions for non-hi-dpi (Retina) displays sadly.

**Comment by kitten** [comment]
Ok, so in the next version I'll try to remove the "special" diacritics that I had for some uppercase letters. They might slightly break out of their boundaries sometimes, but that should be fine. Let's see 💯 

<img width="792" alt="screen shot 2018-05-04 at 18 10 50" src="https://user-images.githubusercontent.com/2041385/39641539-8117b034-4fc6-11e8-852e-2ffde3297bc7.png">

**Comment by kitten** [comment]
Seems to do it; Expect a new release soon :+1:

<img width="288" alt="screen shot 2018-05-04 at 18 26 00" src="https://user-images.githubusercontent.com/2041385/39642165-a7149bce-4fc8-11e8-826e-560710f251a7.png">

**Comment by kitten** [comment]
Fixed and released in `v0.470`. https://dank.sh/releases/

Let me know if there's anything else 🙌

**Comment by hedinne** [comment]
The readability is way up in `v0.470`. Thank you.
