### ISSUE TITLE
Feature Request: More than three ='s

### ISSUE THREAD

**Issue by erikras** [kitten/dank-mono#14]
My ex code font, Fira Code, would treat more than three consecutive `=`'s as individual `=`'s, i.e. not try to convert them into a `n/3` `===` ligatures. Any chance Dank can do that?

## Fira Code

![fira](https://user-images.githubusercontent.com/4396759/39706801-cedba12e-5212-11e8-99a5-b3fe7cb6c342.jpg)

## Dank Mono

![dank](https://user-images.githubusercontent.com/4396759/39706806-d1f86e1e-5212-11e8-9db2-1bba83eb5bf8.jpg)

**Comment by kitten** [comment]
Oh, good catch! I’ll probably have to look up some OpenType feature code stuff on how to make this work 😅

**Comment by svipben** [comment]
![image](https://user-images.githubusercontent.com/10441177/39718422-e8e0818a-523e-11e8-8c63-64e2d8a60ce8.png)

**Comment by kitten** [comment]
Moved to Spectrum https://spectrum.chat/?t=4ec58c5f-38b0-406b-a1fa-107276bc71e6
