### ISSUE TITLE
'2' glyph has different height than other numerals

### ISSUE THREAD

**Issue by swenson** [kitten/dank-mono#15]
See screenshots. I'm using Chrome on Linux with a non-retina 2560x1440 screen, `font-size: 14px`

100% zoom (2 is shorter than other numerals):

![screenshot from 2018-05-07 11-27-04](https://user-images.githubusercontent.com/33404/39718070-08c54ae4-51ea-11e8-9518-c020864e1ddb.png)

90% zoom (2 is shorter than other numerals):

![screenshot from 2018-05-07 11-27-19](https://user-images.githubusercontent.com/33404/39718085-1018b100-51ea-11e8-9c91-785a795469d1.png)

110% Zoom (seems okay):

![screenshot from 2018-05-07 11-27-32](https://user-images.githubusercontent.com/33404/39718100-1be1be78-51ea-11e8-8f3f-053b3ee1cba5.png)

**Comment by kitten** [comment]
This is probably an autohinting problem since I see you’re using the font on a non-hi-dpi display. I’ll have a look :)

**Comment by kitten** [comment]
Moved to Spectrum https://spectrum.chat/?t=021dcd3e-1905-4a10-9d76-cb9e69984ab9
