### ISSUE TITLE
Feature Request: Additional Font Weights

### ISSUE THREAD

**Issue by jacob-beltran** [kitten/dank-mono#16]
First off, Great work on this font. The glyph shapes are quite readable and lovely.

Since I'm on a retina display in VSCode with subpixel antialiasing enabled, I usually prefer a slightly lighter weight font to code in when using a dark background. As you probably know, on macOS, subpixel-antialiased text rendered on a dark background tends to appear heavier  than the equivalent text on a light background due to whatever text rendering algorithm macOS uses.

As a result, I prefer to code in a slightly lighter weight font. I was previously using Fira Code at a font-weight of 300. I much prefer the glyph shapes (and pretty italics) of Dank Mono, but I find the extra heaviness a little hard to adjust to. A lighter weight version would be very much appreciated.

Thanks for the great work!
-Jacob

**Comment by kitten** [comment]
That seems really reasonable. I haven't added any weights yet, since that involves redrawing all of the current glyphs :wink:

Moved to Spectrum https://spectrum.chat/?t=5ea2f26a-ada7-4831-a99d-be43b4589094
