### ISSUE TITLE
Ligature size

### ISSUE THREAD

**Issue by hedinne** [kitten/dank-mono#3]
First of congratulations! 

In my opinion most of the ligatures are to small and squish. 
![dbyw0nrxuayzuya](https://user-images.githubusercontent.com/7573694/39411973-ae4e518c-4c03-11e8-94e5-6fc4101f9d7e.jpg)

This also goes for some math symbols.
![screen shot 2018-04-29 at 23 18 00](https://user-images.githubusercontent.com/7573694/39411982-e5688534-4c03-11e8-8174-97079050da5f.png)

Tested on Mac and PC in VS Code. Font size 16px.

**Comment by spences10** [comment]
Just noticed the `<=` doesn't have a ligature 🙃

**Comment by kitten** [comment]
@spences10 I'll probably need an issue where we can collect some ligatures that I'll need to add. For now, this is probably more of an issue for hairline-ish symbols

**Comment by spences10** [comment]
@kitten I was thinking about logging a new issue. Apologies for hijacking the thread @hedinne 🙏

**Comment by hedinne** [comment]
Yeah, none of the screens I've tested it have been Retina.

**Comment by joshburgess** [comment]
I really like the sizing and general style of the ligatures in Monoid. It's missing a few things compared to FiraCode, but I use it anyway, because I prefer the way it looks. I think it would be a good example to follow.

**Comment by kitten** [comment]
Fixed and released in `v0.470`. https://dank.sh/releases/

Let me know if there's anything else 🙌
