### ISSUE TITLE
Feature request <= ligature 

### ISSUE THREAD

**Issue by spences10** [kitten/dank-mono#6]
Could the `<=` ligature be added please?

![image](https://user-images.githubusercontent.com/234708/39434091-819ead30-4c8f-11e8-8502-fb4ae24ae854.png)

These are examples and not suggestions, I thought they would look like a reverse fat arrow 🙃 so I googled for images

**Comment by kitten** [comment]
So I was kind of careful with those and didn’t include them at first because they’re more than a “contraction” of two glyphs. The trouble would be that it’d look like a single glyph.

Let’s see if more people are into the idea first 🙌

**Comment by spences10** [comment]
It's not urgent, I've never felt a burning desire to have a backwards fat arrow 🙃

**Comment by ekfuhrmann** [comment]
I'm a big fan of font ligatures as well. I've been using `Fira Code iScript` for awhile now in vsCode with ligatures enabled and it works quite well for dealing with combining the glyphs.

Would it not be possible to have ligatures be a feature that can be enabled/disabled based on user preference?

**Comment by fbartho** [comment]
I use "Monoid HalfTight" for the ligatures :) -- I think it does a great job at making wide ligatures that look great without confusing you if you had entered a unicode char!

**Comment by ekfuhrmann** [comment]
I've been really liking ligatures myself. I currently have been using `FiraCode` which has really easy to parse ligatures that work great.

https://github.com/tonsky/FiraCode

**Comment by kitten** [comment]
Superseded by issue #10
