### ISSUE TITLE
fix spacing for "s"

### ISSUE THREAD

**Issue by kgcreative** [kitten/dank-mono#7]
the white space after `s` is a bit off compared to the other letterforms, resulting in words that look like they are split. I first noticed it when writing `const`, and thought the crossbar on the `t` needed adjusting, but visual testing below shows the spacing around the `t` feels good, but spacing after the `s` could be adjusted. My gut reaction recommendation would be to adjust the spine on the right of the `s` to make it occupy a bit more horizontal space, balancing it up.

visual test below:
![screenshot-2018-05-01-02 17 36](https://user-images.githubusercontent.com/3443142/39469747-a133e20a-4cee-11e8-8432-21b75fddcb94.png)

**Comment by kitten** [comment]
This seems to be a spacing issue on the "s" which is now resolved. Based on your feedback I also updated the "t", "j", and all "cross bar" letter diacritics, to match the new "f".

<img width="320" alt="screen shot 2018-05-01 at 11 35 29" src="https://user-images.githubusercontent.com/2041385/39470151-e9e243c6-4d33-11e8-8c2f-e67ba46b1fa2.png">

**Comment by kgcreative** [comment]
So good!

**Comment by kitten** [comment]
Fixed and released in `v0.470`. https://dank.sh/releases/

Let me know if there's anything else 🙌
