### ISSUE TITLE
Increase the comma's size

### ISSUE THREAD

**Issue by morajabi** [kitten/dank-mono#8]
Dank Mono:
<img width="378" alt="screen shot 2018-05-03 at 2 25 38 pm" src="https://user-images.githubusercontent.com/12202757/39570540-df4bb0a4-4edd-11e8-8884-07d861d2ada9.png">

Operator Mono:
<img width="464" alt="screen shot 2018-05-03 at 2 26 16 pm" src="https://user-images.githubusercontent.com/12202757/39570575-f9253f90-4edd-11e8-9720-6f14cb10dea2.png">

I feel like it's too small, but maybe I'll get used to it.

**Comment by morajabi** [comment]
Also the colon and the dot can be a bit ticker

**Comment by kitten** [comment]
This is probably an issue that involves anti-aliasing i.e. hinting and an optical illusion that makes it appear smaller in the first place.

Will be fixed in the next release

**Comment by morajabi** [comment]
FWIW I wear glasses. Awesome!

**Comment by kitten** [comment]
Fixed and released in `v0.470`. https://dank.sh/releases/

Let me know if there's anything else 🙌
