### ISSUE TITLE
Improve Powerline symbol alignment

### ISSUE THREAD

**Issue by vipulmathur** [kitten/dank-mono#9]
Dank is 'taller' than many other fonts, so [powerline](https://github.com/powerline/fonts) in zsh/ vim looks like this:
![image](https://user-images.githubusercontent.com/1270786/39622340-6b8dff00-4faf-11e8-82fd-ccdef4948969.png)
![image](https://user-images.githubusercontent.com/1270786/39622384-a3a9cfae-4faf-11e8-9ca8-f74a81fd8fb4.png)

Can we please fix this?

**Comment by kitten** [comment]
Powerline symbols are already supported; Can you check whether your Terminal app introduces an adjusted line-height or padding per line?

<img width="324" alt="screen shot 2018-05-04 at 12 37 12" src="https://user-images.githubusercontent.com/2041385/39625969-e61c325e-4f97-11e8-82bc-0c17817f22da.png">

Here's what the symbol in question looks like. As you can see it matches maximum height of the glyphs'.

**Comment by kitten** [comment]
Judging from some discussions on the Hack font repository, this is a known issue and indeed related to line heights. I could scale the symbols past the bounding box to account for this, but this will certainly introduce more issues.

I might try a couple of things to sort this out, but it's an issue that solely depends on your Terminal's set up, so it might also be fixable by tweaking paddings and line heights. https://github.com/source-foundry/Hack/pull/234

**Comment by vipulmathur** [comment]
It is not as simple as setting up the terminal with line height adjustments once. The setup seems to be dependent on the point size of the font. So the setup breaks if I make the font bigger or smaller, say when presenting something on a projector, or swithching from a high DPI display to a regular DPI one.



I use [alacritty](https://github.com/jwilm/alacritty) on Arch Linux. Alacritty does allow me to adjust the line spacing by specifying offsets. Here are a few samples with different combination of offsets and point sizes.

14pt, offset.y=0, zoom=0:
![image](https://user-images.githubusercontent.com/1270786/39633966-1d0b8c26-4fd7-11e8-8e70-c7c6d1ff5459.png)

14pt, offset.y=-6, zoom=0: fixes the triangle separator, but now everything is floating too high within the line (see the three stacked lines after 100%)
![image](https://user-images.githubusercontent.com/1270786/39634059-62fd1cb8-4fd7-11e8-8b12-2d1d894f8d82.png)

14pt, offset.y=-6, zoom=+3: the broken triangle separator is back by just zooming in to the window a bit
![image](https://user-images.githubusercontent.com/1270786/39634276-fa7d786c-4fd7-11e8-9961-55b93646d790.png)

The link you include has a wealth of info on this issue. I am sure you will find a reasonable approach to fix this. Thanks for your efforts!

**Comment by kitten** [comment]
I tweaked the sizes a little and it should be better now. fyi I have my Alacritty set to `offset.y = 1.0` and `glyph_offset.y = 2.0`, but that's kind of unrelated and for vertical alignment only.

<img width="373" alt="screen shot 2018-05-05 at 20 52 13" src="https://user-images.githubusercontent.com/2041385/39667084-5a452244-50a6-11e8-900f-4b277aa7ef92.png">

**Comment by vipulmathur** [comment]
Your screenshot above looks great! These changes are not released yet right?

**Comment by kitten** [comment]
Moved to Spectrum https://spectrum.chat/?t=134f35e0-21d3-4e0d-ad2f-e545df47cb75
